name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install SonarScanner
        shell: pwsh
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$HOME/.dotnet/tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check dotnet tools (debugging step)
        shell: pwsh
        run: dotnet tool list --global

      - name: Run SonarQube Analysis
        shell: pwsh
        run: |
          $scannerPath = "$HOME/.dotnet/tools/dotnet-sonarscanner"
          & $scannerPath begin `
            /k:"eShopOnWeb" `
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

          dotnet build eShopOnWeb.sln

          & $scannerPath end `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
